/* =========================================================================
   haug-it.eu — MCU tracker dataset.

   Sourced 2026-09-08 from:
   - Release dates, phases, sagas (core films): Wikipedia, "List of Marvel
     Cinematic Universe films".
   - Tomatometer scores (core films): Rotten Tomatoes editorial,
     "Every Marvel Movie By Release Date" (marvel-movie-release-timeline).
   - Chronological (in-universe) order, positions 1-81: Rotten Tomatoes
     editorial, "Marvel Movies in Order: MCU Chronological & Release Order".
   - Series/special premiere dates and season/episode counts: Wikipedia,
     "List of Marvel Cinematic Universe television series".
   - IMDb ratings (37 films): aggregated via bamsmackpow.com "All 37 MCU
     movies ranked ... according to IMDb", cross-checked against IMDb.
   - Post-credit-scene facts: well-documented for Phase 1-4; Phase 5-6
     entries checked via contemporary reporting (Variety, TIME, ScreenRant,
     Rotten Tomatoes) on 2026-09-08.
   - Essential/skippable tiering: a synthesis of several published
     viewing-order guides (not a single ranking) — see mcu/methodology.html.
   - Non-MCU secondary list: general release-history knowledge, NOT
     individually re-verified against a primary source in this pass —
     treat exact days-of-month there as approximate; see methodology.html.

   Avengers: Doomsday (2026-12-18) and Avengers: Secret Wars (2027-12-17)
   are both officially dated but unreleased. Phase Seven titles without a
   confirmed date (Armor Wars, Nova, a second Shang-Chi, an untitled X-Men
   film, Ghost Rider, Black Panther III) are deliberately left out of this
   dataset for now — the user asked for a tracker "to Doomsday", and
   undated titles would need re-checking on every visit anyway.
   ========================================================================= */

window.MCU_DATA = {
  meta: {
    dataAsOf: "2026-09-08",
    partsVocab: [
      { id: "avengers-core", label: { en: "Avengers", de: "Avengers" } },
      { id: "iron-man", label: { en: "Iron Man", de: "Iron Man" } },
      { id: "hulk", label: { en: "Hulk", de: "Hulk" } },
      { id: "captain-america", label: { en: "Captain America", de: "Captain America" } },
      { id: "thor", label: { en: "Thor", de: "Thor" } },
      { id: "guardians-of-the-galaxy", label: { en: "Guardians of the Galaxy", de: "Guardians of the Galaxy" } },
      { id: "spider-man-mcu", label: { en: "Spider-Man", de: "Spider-Man" } },
      { id: "doctor-strange", label: { en: "Doctor Strange", de: "Doctor Strange" } },
      { id: "black-panther", label: { en: "Black Panther / Wakanda", de: "Black Panther / Wakanda" } },
      { id: "ant-man", label: { en: "Ant-Man", de: "Ant-Man" } },
      { id: "captain-marvel", label: { en: "Captain Marvel", de: "Captain Marvel" } },
      { id: "black-widow", label: { en: "Black Widow", de: "Black Widow" } },
      { id: "eternals", label: { en: "Eternals", de: "Eternals" } },
      { id: "shang-chi", label: { en: "Shang-Chi", de: "Shang-Chi" } },
      { id: "wanda-vision-family", label: { en: "Wanda / Agatha", de: "Wanda / Agatha" } },
      { id: "hawkeye-family", label: { en: "Hawkeye / Young Avengers", de: "Hawkeye / Young Avengers" } },
      { id: "agent-carter", label: { en: "Agent Carter", de: "Agent Carter" } },
      { id: "nick-fury", label: { en: "Nick Fury / SWORD", de: "Nick Fury / SWORD" } },
      { id: "fantastic-four", label: { en: "Fantastic Four", de: "Fantastic Four" } },
      { id: "thunderbolts", label: { en: "Thunderbolts / New Avengers", de: "Thunderbolts / New Avengers" } },
      { id: "multiverse-saga", label: { en: "Multiverse Saga core", de: "Multiverse Saga (Kern)" } },
      { id: "street-level", label: { en: "Street-level heroes", de: "Straßen-Level-Helden" } },
      { id: "x-men-fox", label: { en: "X-Men (Fox)", de: "X-Men (Fox)" } },
      { id: "wolverine-deadpool", label: { en: "Wolverine / Deadpool", de: "Wolverine / Deadpool" } }
    ]
  },

  core: [
    // ---------- Marvel One-Shots ----------
    { id: "one-shot-consultant", title: "Marvel One-Shot: The Consultant", category: "short", releaseDate: "2011-09-13", released: true, phase: 1, saga: "infinity", runtimeMinutes: 8, seasons: null, timelineOrder: 12, releaseOrder: null, parts: ["avengers-core"], postCredit: { mid: false, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: 7.1, tmdbId: null, essentialTier: "optional", tierNote: "Bridges Incredible Hulk and The Avengers; fun, not required." },
    { id: "one-shot-thors-hammer", title: "Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer", category: "short", releaseDate: "2011-10-25", released: true, phase: 1, saga: "infinity", runtimeMinutes: 4, seasons: null, timelineOrder: 10, releaseOrder: null, parts: ["thor"], postCredit: { mid: false, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: 7.2, tmdbId: null, essentialTier: "optional", tierNote: "Coulson comedy bit, no plot weight." },
    { id: "one-shot-item-47", title: "Item 47", category: "short", releaseDate: "2012-09-25", released: true, phase: 1, saga: "infinity", runtimeMinutes: 12, seasons: null, timelineOrder: 14.5, releaseOrder: null, parts: ["avengers-core"], postCredit: { mid: false, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: 7.1, tmdbId: null, essentialTier: "optional", tierNote: "Post-Battle-of-New-York cleanup vignette." },
    { id: "one-shot-agent-carter", title: "Marvel One-Shot: Agent Carter", category: "short", releaseDate: "2013-09-03", released: true, phase: 1, saga: "infinity", runtimeMinutes: 15, seasons: null, timelineOrder: 3, releaseOrder: null, parts: ["agent-carter"], postCredit: { mid: false, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: 7.7, tmdbId: null, essentialTier: "optional", tierNote: "Seed for the Agent Carter series." },

    // ---------- Phase One ----------
    { id: "iron-man", title: "Iron Man", category: "film", releaseDate: "2008-05-02", released: true, phase: 1, saga: "infinity", runtimeMinutes: 126, seasons: null, timelineOrder: 7, releaseOrder: 1, parts: ["avengers-core", "iron-man"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 94, audienceScore: 91, imdbRating: 7.9, tmdbId: 1726, essentialTier: "essential", tierNote: "The MCU's founding film." },
    { id: "incredible-hulk", title: "The Incredible Hulk", category: "film", releaseDate: "2008-06-13", released: true, phase: 1, saga: "infinity", runtimeMinutes: 112, seasons: null, timelineOrder: 9, releaseOrder: 2, parts: ["hulk"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 68, audienceScore: 70, imdbRating: 6.6, tmdbId: 1724, essentialTier: "skippable", tierNote: "Widely cited as the most skippable Phase 1 entry; almost nothing carries forward." },
    { id: "iron-man-2", title: "Iron Man 2", category: "film", releaseDate: "2010-05-07", released: true, phase: 1, saga: "infinity", runtimeMinutes: 124, seasons: null, timelineOrder: 8, releaseOrder: 3, parts: ["avengers-core", "iron-man"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 72, audienceScore: 71, imdbRating: 6.9, tmdbId: 10138, essentialTier: "skippable", tierNote: "Sets up SHIELD/Avengers Initiative but is commonly listed as skippable filler." },
    { id: "thor", title: "Thor", category: "film", releaseDate: "2011-05-06", released: true, phase: 1, saga: "infinity", runtimeMinutes: 115, seasons: null, timelineOrder: 11, releaseOrder: 4, parts: ["avengers-core", "thor"], postCredit: { mid: true, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: 77, audienceScore: 76, imdbRating: 7.0, tmdbId: 10195, essentialTier: "recommended", tierNote: "Introduces Loki and Asgard." },
    { id: "captain-america-first-avenger", title: "Captain America: The First Avenger", category: "film", releaseDate: "2011-07-22", released: true, phase: 1, saga: "infinity", runtimeMinutes: 124, seasons: null, timelineOrder: 2, releaseOrder: 5, parts: ["avengers-core", "captain-america"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 80, audienceScore: 74, imdbRating: 6.9, tmdbId: 1771, essentialTier: "essential", tierNote: "Earliest MCU film chronologically; sets up the Tesseract thread." },
    { id: "the-avengers", title: "The Avengers", category: "film", releaseDate: "2012-05-04", released: true, phase: 1, saga: "infinity", runtimeMinutes: 143, seasons: null, timelineOrder: 13, releaseOrder: 6, parts: ["avengers-core"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 91, audienceScore: 91, imdbRating: 8.0, tmdbId: 24428, essentialTier: "essential", tierNote: "First team-up, the Phase 1 payoff." },

    // ---------- Phase Two ----------
    { id: "iron-man-3", title: "Iron Man 3", category: "film", releaseDate: "2013-05-03", released: true, phase: 2, saga: "infinity", runtimeMinutes: 130, seasons: null, timelineOrder: 16, releaseOrder: 7, parts: ["iron-man"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 79, audienceScore: 78, imdbRating: 7.1, tmdbId: 68721, essentialTier: "recommended", tierNote: "Closes Tony's post-New York PTSD arc." },
    { id: "thor-dark-world", title: "Thor: The Dark World", category: "film", releaseDate: "2013-11-08", released: true, phase: 2, saga: "infinity", runtimeMinutes: 112, seasons: null, timelineOrder: 15, releaseOrder: 8, parts: ["thor"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 67, audienceScore: 76, imdbRating: 6.8, tmdbId: 76338, essentialTier: "skippable", tierNote: "Mid-credits sets up the Collector, otherwise low plot weight until Endgame briefly reuses the Reality Stone/Jane thread." },
    { id: "captain-america-winter-soldier", title: "Captain America: The Winter Soldier", category: "film", releaseDate: "2014-04-04", released: true, phase: 2, saga: "infinity", runtimeMinutes: 136, seasons: null, timelineOrder: 17, releaseOrder: 9, parts: ["avengers-core", "captain-america"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 90, audienceScore: 91, imdbRating: 7.7, tmdbId: 100402, essentialTier: "essential", tierNote: "Dismantles SHIELD/HYDRA — reshapes the entire saga." },
    { id: "guardians-of-the-galaxy", title: "Guardians of the Galaxy", category: "film", releaseDate: "2014-08-01", released: true, phase: 2, saga: "infinity", runtimeMinutes: 121, seasons: null, timelineOrder: 18, releaseOrder: 10, parts: ["guardians-of-the-galaxy"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 91, audienceScore: 92, imdbRating: 8.0, tmdbId: 118340, essentialTier: "essential", tierNote: "Introduces the cosmic side of the MCU." },
    { id: "i-am-groot", title: "I Am Groot", category: "series", releaseDate: "2022-08-10", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 5, releaseDate: "2022-08-10", avgEpisodeMinutes: 5 }], timelineOrder: 19, releaseOrder: null, parts: ["guardians-of-the-galaxy"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 92, audienceScore: 60, imdbRating: 6.3, tmdbId: 121659, essentialTier: "optional", tierNote: "Five very short Groot vignettes, no plot weight." },
    { id: "avengers-age-of-ultron", title: "Avengers: Age of Ultron", category: "film", releaseDate: "2015-05-01", released: true, phase: 2, saga: "infinity", runtimeMinutes: 141, seasons: null, timelineOrder: 23, releaseOrder: 11, parts: ["avengers-core"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 75, audienceScore: 83, imdbRating: 7.3, tmdbId: 99861, essentialTier: "essential", tierNote: "Introduces Vision, Wanda, Pietro; sets up Civil War and Infinity Stone stakes." },
    { id: "ant-man", title: "Ant-Man", category: "film", releaseDate: "2015-07-17", released: true, phase: 2, saga: "infinity", runtimeMinutes: 117, seasons: null, timelineOrder: 24, releaseOrder: 12, parts: ["ant-man"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 79, audienceScore: 84, imdbRating: 7.2, tmdbId: 102899, essentialTier: "recommended", tierNote: "Introduces the Quantum Realm, later central to Endgame." },

    // ---------- Marvel Television (Netflix) — kept as core-adjacent per RT's own chronology but flagged non-MCU below ----------

    // ---------- Phase Three ----------
    { id: "captain-america-civil-war", title: "Captain America: Civil War", category: "film", releaseDate: "2016-05-06", released: true, phase: 3, saga: "infinity", runtimeMinutes: 147, seasons: null, timelineOrder: 29, releaseOrder: 13, parts: ["avengers-core", "captain-america", "spider-man-mcu"], postCredit: { mid: true, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: 90, audienceScore: 89, imdbRating: 7.8, tmdbId: 271110, essentialTier: "essential", tierNote: "Splits the Avengers; introduces MCU Spider-Man and Black Panther." },
    { id: "doctor-strange", title: "Doctor Strange", category: "film", releaseDate: "2016-11-04", released: true, phase: 3, saga: "infinity", runtimeMinutes: 115, seasons: null, timelineOrder: 35, releaseOrder: 14, parts: ["doctor-strange"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 89, audienceScore: 86, imdbRating: 7.5, tmdbId: 284052, essentialTier: "essential", tierNote: "Introduces magic/multiverse concepts central to Phase 4-6." },
    { id: "guardians-vol-2", title: "Guardians of the Galaxy Vol. 2", category: "film", releaseDate: "2017-05-05", released: true, phase: 3, saga: "infinity", runtimeMinutes: 137, seasons: null, timelineOrder: 20, releaseOrder: 15, parts: ["guardians-of-the-galaxy"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 85, audienceScore: 87, imdbRating: 7.6, tmdbId: 283995, essentialTier: "essential", tierNote: "Five separate post-credit scenes; several matter for Vol. 3." },
    { id: "spider-man-homecoming", title: "Spider-Man: Homecoming", category: "film", releaseDate: "2017-07-07", released: true, phase: 3, saga: "infinity", runtimeMinutes: 133, seasons: null, timelineOrder: 33, releaseOrder: 16, parts: ["spider-man-mcu", "avengers-core"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 92, audienceScore: 88, imdbRating: 7.4, tmdbId: 315635, essentialTier: "essential", tierNote: "Peter's MCU coming-of-age story." },
    { id: "thor-ragnarok", title: "Thor: Ragnarok", category: "film", releaseDate: "2017-11-03", released: true, phase: 3, saga: "infinity", runtimeMinutes: 130, seasons: null, timelineOrder: 40, releaseOrder: 17, parts: ["thor", "avengers-core"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 93, audienceScore: 87, imdbRating: 7.9, tmdbId: 284053, essentialTier: "essential", tierNote: "Destroys Asgard, sets up Infinity War directly." },
    { id: "black-panther", title: "Black Panther", category: "film", releaseDate: "2018-02-16", released: true, phase: 3, saga: "infinity", runtimeMinutes: 134, seasons: null, timelineOrder: 32, releaseOrder: 18, parts: ["black-panther", "avengers-core"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 96, audienceScore: 79, imdbRating: 7.3, tmdbId: 284054, essentialTier: "essential", tierNote: "Introduces Wakanda properly; highest-rated Phase 3 film." },
    { id: "avengers-infinity-war", title: "Avengers: Infinity War", category: "film", releaseDate: "2018-04-27", released: true, phase: 3, saga: "infinity", runtimeMinutes: 149, seasons: null, timelineOrder: 44, releaseOrder: 19, parts: ["avengers-core"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 85, audienceScore: 91, imdbRating: 8.4, tmdbId: 299536, essentialTier: "essential", tierNote: "The Infinity Saga's central crossover." },
    { id: "ant-man-and-the-wasp", title: "Ant-Man and the Wasp", category: "film", releaseDate: "2018-07-06", released: true, phase: 3, saga: "infinity", runtimeMinutes: 118, seasons: null, timelineOrder: 43, releaseOrder: 20, parts: ["ant-man"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 87, audienceScore: 82, imdbRating: 7.0, tmdbId: 363088, essentialTier: "recommended", tierNote: "End-credits scene (the Snap hitting Hank/Janet/Hope) matters for Endgame." },
    { id: "captain-marvel", title: "Captain Marvel", category: "film", releaseDate: "2019-03-08", released: true, phase: 3, saga: "infinity", runtimeMinutes: 123, seasons: null, timelineOrder: 6, releaseOrder: 21, parts: ["captain-marvel", "nick-fury"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 79, audienceScore: 78, imdbRating: 6.8, tmdbId: 299537, essentialTier: "recommended", tierNote: "Sets up her role in Endgame and the pager thread." },
    { id: "avengers-endgame", title: "Avengers: Endgame", category: "film", releaseDate: "2019-04-26", released: true, phase: 3, saga: "infinity", runtimeMinutes: 181, seasons: null, timelineOrder: 45, releaseOrder: 22, parts: ["avengers-core"], postCredit: { mid: false, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: 94, audienceScore: 90, imdbRating: 8.4, tmdbId: 299534, essentialTier: "essential", tierNote: "Closes the Infinity Saga. No post-credit scene (a deliberate first)." },
    { id: "spider-man-far-from-home", title: "Spider-Man: Far From Home", category: "film", releaseDate: "2019-07-02", released: true, phase: 3, saga: "infinity", runtimeMinutes: 129, seasons: null, timelineOrder: 52, releaseOrder: 23, parts: ["spider-man-mcu"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 91, audienceScore: 88, imdbRating: 7.4, tmdbId: 429617, essentialTier: "essential", tierNote: "Mid-credits reveal directly sets up No Way Home." },

    // ---------- Phase Four ----------
    { id: "wandavision", title: "WandaVision", category: "series", releaseDate: "2021-01-15", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 9, releaseDate: "2021-01-15", avgEpisodeMinutes: 35 }], timelineOrder: 47, releaseOrder: 1, parts: ["wanda-vision-family", "avengers-core"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 91, audienceScore: 75, imdbRating: 7.9, tmdbId: 85271, essentialTier: "essential", tierNote: "Opens the Multiverse Saga; direct setup for Multiverse of Madness and Agatha." },
    { id: "falcon-winter-soldier", title: "The Falcon and the Winter Soldier", category: "series", releaseDate: "2021-03-19", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 6, releaseDate: "2021-03-19", avgEpisodeMinutes: 50 }], timelineOrder: 51, releaseOrder: 2, parts: ["captain-america"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 84, audienceScore: 74, imdbRating: 7.4, tmdbId: 88396, essentialTier: "recommended", tierNote: "Sam becomes Captain America — pays off in Brave New World." },
    { id: "loki-s1", title: "Loki", category: "series", releaseDate: "2021-06-09", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 6, releaseDate: "2021-06-09", avgEpisodeMinutes: 50 }, { season: 2, episodes: 6, releaseDate: "2023-10-05", avgEpisodeMinutes: 50 }], timelineOrder: 48, releaseOrder: 3, parts: ["avengers-core", "multiverse-saga"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 92, audienceScore: 84, imdbRating: 8.2, tmdbId: 84958, essentialTier: "essential", tierNote: "Creates the multiverse branching that drives the whole current saga." },
    { id: "what-if-s1", title: "What If...?", category: "series", releaseDate: "2021-08-11", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 9, releaseDate: "2021-08-11", avgEpisodeMinutes: 33,
        /* Anthology: each episode diverges from the main timeline at a different point. timelineOrder values below
           are approximate point-of-divergence placements for the "story timeline" sort, not a claim about a single
           canonical position — see mcu/methodology.html. Episodes without an entry here fall back to the season's
           own timelineOrder (57). */
        episodeTimeline: [
          { episode: 1, timelineOrder: 1.6, note: "Diverges at Captain America: The First Avenger (Peggy takes the serum)." },
          { episode: 2, timelineOrder: 18.2, note: "Diverges from young Star-Lord's 1988 abduction, the same event as the mainline Guardians backstory." },
          { episode: 3, timelineOrder: 7.4, note: "Diverges in the early Phase One window (Hank Pym/SHIELD recruitment instead of the Avengers)." },
          { episode: 4, timelineOrder: 35.2, note: "Diverges at Doctor Strange's car-crash origin." },
          { episode: 5, timelineOrder: 24.2, note: "Diverges from a Pym Particle experiment going wrong around the Ant-Man era." },
          { episode: 6, timelineOrder: 7.2, note: "Diverges at Tony Stark's origin in Afghanistan." },
          { episode: 7, timelineOrder: 1.4, note: "Diverges in Asgard's ancient past, before Loki is adopted." },
          { episode: 8, timelineOrder: 23.2, note: "Diverges at Avengers: Age of Ultron." },
          { episode: 9, timelineOrder: 57, note: "Present-day framing story that ties the season together — no earlier divergence point of its own." }
        ]
      }, { season: 2, episodes: 9, releaseDate: "2023-12-22", avgEpisodeMinutes: 33 }, { season: 3, episodes: 8, releaseDate: "2024-12-22", avgEpisodeMinutes: 33 }], timelineOrder: 57, releaseOrder: 4, parts: ["multiverse-saga"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 87, audienceScore: 65, imdbRating: 7.4, tmdbId: 92783, essentialTier: "recommended", tierNote: "Animated multiverse anthology; Season 1's episodes each diverge at a different point in the main timeline (see its detail view); the finale sets up the Watcher's role." },
    { id: "black-widow", title: "Black Widow", category: "film", releaseDate: "2021-07-09", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 134, seasons: null, timelineOrder: 31, releaseOrder: 24, parts: ["black-widow", "avengers-core"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 79, audienceScore: 91, imdbRating: 6.7, tmdbId: 497698, essentialTier: "skippable", tierNote: "A prequel; not required to follow Natasha's arc in the main saga, but introduces Yelena." },
    { id: "shang-chi", title: "Shang-Chi and the Legend of the Ten Rings", category: "film", releaseDate: "2021-09-03", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 132, seasons: null, timelineOrder: 50, releaseOrder: 25, parts: ["shang-chi"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 92, audienceScore: 90, imdbRating: 7.4, tmdbId: 566525, essentialTier: "essential", tierNote: "The Ten Rings thread feeds directly into the current saga's endgame." },
    { id: "eternals", title: "Eternals", category: "film", releaseDate: "2021-11-05", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 156, seasons: null, timelineOrder: 53, releaseOrder: 26, parts: ["eternals"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 48, audienceScore: 76, imdbRating: 6.3, tmdbId: 524434, essentialTier: "skippable", tierNote: "Lowest Tomatometer score of any MCU film to date; mid-credits introduces Eros, otherwise self-contained." },
    { id: "hawkeye", title: "Hawkeye", category: "series", releaseDate: "2021-11-24", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 6, releaseDate: "2021-11-24", avgEpisodeMinutes: 45 }], timelineOrder: 56, releaseOrder: 5, parts: ["hawkeye-family"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 91, audienceScore: 90, imdbRating: 7.6, tmdbId: 88329, essentialTier: "recommended", tierNote: "Introduces Kate Bishop and Yelena's contract on Clint." },
    { id: "spider-man-no-way-home", title: "Spider-Man: No Way Home", category: "film", releaseDate: "2021-12-17", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 148, seasons: null, timelineOrder: 54, releaseOrder: 27, parts: ["spider-man-mcu", "multiverse-saga"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 93, audienceScore: 98, imdbRating: 8.2, tmdbId: 634649, essentialTier: "essential", tierNote: "Formally opens the multiverse to crossovers with the non-MCU Spider-Man films." },
    { id: "moon-knight", title: "Moon Knight", category: "series", releaseDate: "2022-03-30", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 6, releaseDate: "2022-03-30", avgEpisodeMinutes: 47 }], timelineOrder: 58, releaseOrder: 6, parts: [], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 87, audienceScore: 75, imdbRating: 7.3, tmdbId: 91363, essentialTier: "optional", tierNote: "Self-contained; no confirmed follow-up yet." },
    { id: "doctor-strange-multiverse-of-madness", title: "Doctor Strange in the Multiverse of Madness", category: "film", releaseDate: "2022-05-06", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 126, seasons: null, timelineOrder: 55, releaseOrder: 28, parts: ["doctor-strange", "multiverse-saga"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 73, audienceScore: 78, imdbRating: 6.9, tmdbId: 453395, essentialTier: "essential", tierNote: "Direct sequel to WandaVision; introduces the Illuminati and multiverse incursions." },
    { id: "ms-marvel", title: "Ms. Marvel", category: "series", releaseDate: "2022-06-08", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 6, releaseDate: "2022-06-08", avgEpisodeMinutes: 40 }], timelineOrder: 62, releaseOrder: 7, parts: ["hawkeye-family"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 98, audienceScore: 45, imdbRating: 6.1, tmdbId: null, essentialTier: "recommended", tierNote: "Introduces Kamala Khan ahead of The Marvels." },
    { id: "thor-love-and-thunder", title: "Thor: Love and Thunder", category: "film", releaseDate: "2022-07-08", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 119, seasons: null, timelineOrder: 63, releaseOrder: 29, parts: ["thor"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 64, audienceScore: 63, imdbRating: 6.2, tmdbId: 616037, essentialTier: "optional", tierNote: "Mostly self-contained; mid-credits introduces Hercules." },
    { id: "she-hulk", title: "She-Hulk: Attorney at Law", category: "series", releaseDate: "2022-08-18", released: true, phase: 4, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 9, releaseDate: "2022-08-18", avgEpisodeMinutes: 32 }], timelineOrder: 61, releaseOrder: 8, parts: ["hulk"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 82, audienceScore: 38, imdbRating: 5.6, tmdbId: null, essentialTier: "optional", tierNote: "Mostly self-contained, breaks the fourth wall." },
    { id: "werewolf-by-night", title: "Werewolf by Night", category: "special", releaseDate: "2022-10-07", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 53, seasons: null, timelineOrder: 64, releaseOrder: null, parts: [], postCredit: { mid: false, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: 97, audienceScore: 88, imdbRating: 7.5, tmdbId: 1073362, essentialTier: "optional", tierNote: "Standalone horror one-off, black-and-white, no ties to the wider plot yet." },
    { id: "black-panther-wakanda-forever", title: "Black Panther: Wakanda Forever", category: "film", releaseDate: "2022-11-11", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 161, seasons: null, timelineOrder: 59, releaseOrder: 30, parts: ["black-panther"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 84, audienceScore: 94, imdbRating: 6.7, tmdbId: 505642, essentialTier: "recommended", tierNote: "Introduces Namor and Ironheart's suit." },
    { id: "guardians-holiday-special", title: "The Guardians of the Galaxy Holiday Special", category: "special", releaseDate: "2022-11-25", released: true, phase: 4, saga: "multiverse", runtimeMinutes: 44, seasons: null, timelineOrder: 66, releaseOrder: null, parts: ["guardians-of-the-galaxy"], postCredit: { mid: false, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: 91, audienceScore: 74, imdbRating: 7.5, tmdbId: 1058151, essentialTier: "optional", tierNote: "Fun bridge to Vol. 3, not required." },

    // ---------- Phase Five ----------
    { id: "ant-man-quantumania", title: "Ant-Man and the Wasp: Quantumania", category: "film", releaseDate: "2023-02-17", released: true, phase: 5, saga: "multiverse", runtimeMinutes: 125, seasons: null, timelineOrder: 68, releaseOrder: 31, parts: ["ant-man", "multiverse-saga"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 46, audienceScore: 75, imdbRating: 6.1, tmdbId: 640146, essentialTier: "skippable", tierNote: "Introduced Kang as the next big threat, but that plan changed after Jonathan Majors' recasting; now widely rated skippable." },
    { id: "guardians-vol-3", title: "Guardians of the Galaxy Vol. 3", category: "film", releaseDate: "2023-05-05", released: true, phase: 5, saga: "multiverse", runtimeMinutes: 150, seasons: null, timelineOrder: 69, releaseOrder: 32, parts: ["guardians-of-the-galaxy"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 82, audienceScore: 94, imdbRating: 7.9, tmdbId: 447365, essentialTier: "essential", tierNote: "Closes out the original Guardians line-up's story." },
    { id: "secret-invasion", title: "Secret Invasion", category: "series", releaseDate: "2023-06-21", released: true, phase: 5, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 6, releaseDate: "2023-06-21", avgEpisodeMinutes: 45 }], timelineOrder: 70, releaseOrder: 9, parts: ["nick-fury"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 54, audienceScore: 23, imdbRating: 5.8, tmdbId: 108978, essentialTier: "recommended", tierNote: "Reshapes Nick Fury's status and the Skrulls' role going forward." },
    { id: "echo", title: "Echo", category: "series", releaseDate: "2024-01-09", released: true, phase: 5, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 5, releaseDate: "2024-01-09", avgEpisodeMinutes: 45 }], timelineOrder: 60, releaseOrder: 10, parts: ["street-level"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 73, audienceScore: 66, imdbRating: 6.2, tmdbId: 202085, essentialTier: "optional", tierNote: "Ties into Daredevil: Born Again but is self-contained on its own." },
    { id: "the-marvels", title: "The Marvels", category: "film", releaseDate: "2023-11-10", released: true, phase: 5, saga: "multiverse", runtimeMinutes: 105, seasons: null, timelineOrder: 71, releaseOrder: 33, parts: ["captain-marvel", "hawkeye-family"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 63, audienceScore: 74, imdbRating: 5.5, tmdbId: 609681, essentialTier: "optional", tierNote: "Lowest-grossing MCU film; end-credits sets up the Young Avengers." },
    { id: "agatha-all-along", title: "Agatha All Along", category: "series", releaseDate: "2024-09-18", released: true, phase: 5, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 9, releaseDate: "2024-09-18", avgEpisodeMinutes: 40 }], timelineOrder: 74, releaseOrder: 11, parts: ["wanda-vision-family"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 92, audienceScore: 72, imdbRating: 7.5, tmdbId: 108964, essentialTier: "recommended", tierNote: "Direct WandaVision spin-off; sets up Billy Maximoff / Young Avengers." },
    { id: "deadpool-wolverine", title: "Deadpool & Wolverine", category: "film", releaseDate: "2024-07-26", released: true, phase: 5, saga: "multiverse", runtimeMinutes: 128, seasons: null, timelineOrder: 49, releaseOrder: 34, parts: ["wolverine-deadpool", "multiverse-saga", "x-men-fox"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 77, audienceScore: 94, imdbRating: 7.5, tmdbId: 533535, essentialTier: "essential", tierNote: "Formally folds the Fox X-Men universe into the MCU multiverse." },
    { id: "your-friendly-neighborhood-spider-man-s1", title: "Your Friendly Neighborhood Spider-Man", category: "series", releaseDate: "2025-01-29", released: true, phase: 5, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 10, releaseDate: "2025-01-29", avgEpisodeMinutes: 25 }, { season: 2, episodes: null, releaseDate: "2027-01-01", avgEpisodeMinutes: 25 }], timelineOrder: 30, releaseOrder: 12, parts: ["spider-man-mcu"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "optional", tierNote: "Animated, set early in Peter's career; parallel side-story." },
    { id: "daredevil-born-again-s1", title: "Daredevil: Born Again", category: "series", releaseDate: "2025-03-04", released: true, phase: 5, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 9, releaseDate: "2025-03-04", avgEpisodeMinutes: 50 }, { season: 2, episodes: 8, releaseDate: "2026-03-24", avgEpisodeMinutes: 50 }], timelineOrder: 76, releaseOrder: 13, parts: ["street-level"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 93, audienceScore: 88, imdbRating: 7.8, tmdbId: 202555, essentialTier: "recommended", tierNote: "Brings Matt Murdock and Wilson Fisk fully into the core MCU." },
    { id: "captain-america-brave-new-world", title: "Captain America: Brave New World", category: "film", releaseDate: "2025-02-14", released: true, phase: 5, saga: "multiverse", runtimeMinutes: 118, seasons: null, timelineOrder: 77, releaseOrder: 35, parts: ["captain-america", "avengers-core"], postCredit: { mid: true, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: 46, audienceScore: 84, imdbRating: 5.6, tmdbId: 822119, essentialTier: "essential", tierNote: "Sam Wilson begins reassembling a new Avengers team." },
    { id: "ironheart", title: "Ironheart", category: "series", releaseDate: "2025-06-24", released: true, phase: 5, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 6, releaseDate: "2025-06-24", avgEpisodeMinutes: 45 }], timelineOrder: 65, releaseOrder: 14, parts: ["black-panther", "iron-man"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "recommended", tierNote: "Riri Williams' path toward the New Avengers/Young Avengers threads." },
    { id: "thunderbolts", title: "Thunderbolts*", category: "film", releaseDate: "2025-05-02", released: true, phase: 5, saga: "multiverse", runtimeMinutes: 127, seasons: null, timelineOrder: 78, releaseOrder: 36, parts: ["thunderbolts", "avengers-core"], postCredit: { mid: false, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 88, audienceScore: 90, imdbRating: 7.1, tmdbId: 986056, essentialTier: "essential", tierNote: "The team becomes 'The New Avengers'; end-credits ties straight into Fantastic Four/Doomsday." },

    // ---------- Phase Six ----------
    { id: "eyes-of-wakanda", title: "Eyes of Wakanda", category: "series", releaseDate: "2025-08-01", released: true, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 4, releaseDate: "2025-08-01", avgEpisodeMinutes: 30 }], timelineOrder: 1, releaseOrder: 15, parts: ["black-panther"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: 92, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "optional", tierNote: "Anthology set across Wakandan history from 1260 BCE onward — earliest MCU chronology, but self-contained." },
    { id: "fantastic-four-first-steps", title: "The Fantastic Four: First Steps", category: "film", releaseDate: "2025-07-25", released: true, phase: 6, saga: "multiverse", runtimeMinutes: 115, seasons: null, timelineOrder: 5, releaseOrder: 37, parts: ["fantastic-four"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 86, audienceScore: 88, imdbRating: 6.8, tmdbId: 617126, essentialTier: "essential", tierNote: "Set on an alternate retro-future Earth; mid-credits scene is a direct Avengers: Doomsday setup." },
    { id: "marvel-zombies", title: "Marvel Zombies", category: "series", releaseDate: "2025-09-24", released: true, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 4, releaseDate: "2025-09-24", avgEpisodeMinutes: 40 }], timelineOrder: 46, releaseOrder: 16, parts: ["multiverse-saga"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "optional", tierNote: "What If...?-adjacent alternate-universe horror anthology." },
    { id: "wonder-man", title: "Wonder Man", category: "series", releaseDate: "2026-01-27", released: true, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 8, releaseDate: "2026-01-27", avgEpisodeMinutes: 40 }], timelineOrder: 67, releaseOrder: 17, parts: ["avengers-core"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "recommended", tierNote: "Simon Williams; industry-satire tone, ties to the wider Avengers roster." },
    { id: "punisher-one-last-kill", title: "The Punisher: One Last Kill", category: "special", releaseDate: "2026-05-12", released: true, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: null, timelineOrder: 80, releaseOrder: null, parts: ["street-level"], postCredit: { mid: false, end: false }, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "optional", tierNote: "Frank Castle special presentation, folded into core MCU continuity (distinct from the 2017-19 Netflix Punisher)." },
    { id: "spider-man-brand-new-day", title: "Spider-Man: Brand New Day", category: "film", releaseDate: "2026-07-31", released: true, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: null, timelineOrder: 81, releaseOrder: 38, parts: ["spider-man-mcu", "avengers-core"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: 90, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "essential", tierNote: "Peter fully rejoins the main Avengers-adjacent cast ahead of Doomsday." },
    { id: "visionquest", title: "VisionQuest", category: "series", releaseDate: "2026-10-14", released: false, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 1, episodes: 8, releaseDate: "2026-10-14", avgEpisodeMinutes: 40 }], timelineOrder: 82, releaseOrder: 18, parts: ["wanda-vision-family"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "recommended", tierNote: "Vision's own series; direct WandaVision follow-up, unreleased as of this data's capture date." },
    { id: "avengers-doomsday", title: "Avengers: Doomsday", category: "film", releaseDate: "2026-12-18", released: false, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: null, timelineOrder: 83, releaseOrder: 39, parts: ["avengers-core", "multiverse-saga", "x-men-fox"], postCredit: { mid: true, end: true }, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "essential", tierNote: "The Multiverse Saga's central crossover; unreleased. Post-credit fields are the announced format, not confirmed content." },
    { id: "your-friendly-neighborhood-spider-man-s2", title: "Your Friendly Neighborhood Spider-Man (Season 2)", category: "series", releaseDate: "2027-01-01", released: false, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: [{ season: 2, episodes: null, releaseDate: "2027-01-01", avgEpisodeMinutes: 25 }], timelineOrder: 84, releaseOrder: 19, parts: ["spider-man-mcu"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "optional", tierNote: "Date and episode count approximate/announced only." },
    { id: "avengers-secret-wars", title: "Avengers: Secret Wars", category: "film", releaseDate: "2027-12-17", released: false, phase: 6, saga: "multiverse", runtimeMinutes: null, seasons: null, timelineOrder: 85, releaseOrder: 40, parts: ["avengers-core", "multiverse-saga"], postCredit: null, isNonMCU: false, nonMCUGroup: null, criticScore: null, audienceScore: null, imdbRating: null, tmdbId: null, essentialTier: "essential", tierNote: "Announced closer of the Multiverse Saga; beyond the 'to Doomsday' scope but included since it already has a confirmed date." }
  ],

  nonMcu: [
    // ---------- Marvel Television (pre-2019, ABC) ----------
    { id: "agents-of-shield", title: "Agents of S.H.I.E.L.D.", category: "series", releaseDate: "2013-09-24", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 22, releaseDate: "2013-09-24", avgEpisodeMinutes: 43 }, { season: 2, episodes: 22, releaseDate: "2014-09-23", avgEpisodeMinutes: 43 }, { season: 3, episodes: 22, releaseDate: "2015-09-29", avgEpisodeMinutes: 43 }, { season: 4, episodes: 22, releaseDate: "2016-09-20", avgEpisodeMinutes: 43 }, { season: 5, episodes: 22, releaseDate: "2017-12-01", avgEpisodeMinutes: 43 }, { season: 6, episodes: 13, releaseDate: "2019-05-10", avgEpisodeMinutes: 43 }, { season: 7, episodes: 13, releaseDate: "2020-05-27", avgEpisodeMinutes: 43 }], timelineOrder: 1001, releaseOrder: 1, parts: ["nick-fury", "street-level"], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-television-abc", criticScore: 82, audienceScore: 89, imdbRating: 7.4, tmdbId: 1403, essentialTier: null, tierNote: "Marvel Studios itself does not treat this as MCU canon; shares occasional references only." },
    { id: "agent-carter-series", title: "Marvel's Agent Carter", category: "series", releaseDate: "2015-01-06", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 8, releaseDate: "2015-01-06", avgEpisodeMinutes: 43 }, { season: 2, episodes: 10, releaseDate: "2016-01-19", avgEpisodeMinutes: 43 }], timelineOrder: 1002, releaseOrder: 2, parts: ["agent-carter"], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-television-abc", criticScore: 88, audienceScore: 85, imdbRating: 7.7, tmdbId: 61550, essentialTier: null, tierNote: "Well-regarded but not MCU-canon per Marvel Studios." },
    { id: "inhumans", title: "Inhumans", category: "series", releaseDate: "2017-09-01", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 8, releaseDate: "2017-09-01", avgEpisodeMinutes: 43 }], timelineOrder: 1003, releaseOrder: 3, parts: [], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-television-abc", criticScore: 11, audienceScore: 34, imdbRating: 5.2, tmdbId: null, essentialTier: null, tierNote: "Poorly received; disconnected from the MCU's later Inhumans references." },
    { id: "runaways", title: "Marvel's Runaways", category: "series", releaseDate: "2017-11-21", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 10, releaseDate: "2017-11-21", avgEpisodeMinutes: 45 }, { season: 2, episodes: 13, releaseDate: "2018-12-21", avgEpisodeMinutes: 45 }, { season: 3, episodes: 10, releaseDate: "2019-12-13", avgEpisodeMinutes: 45 }], timelineOrder: 1004, releaseOrder: 4, parts: [], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-television-abc", criticScore: 74, audienceScore: 66, imdbRating: 6.5, tmdbId: null, essentialTier: null, tierNote: "Hulu original, own continuity." },
    { id: "cloak-and-dagger", title: "Marvel's Cloak & Dagger", category: "series", releaseDate: "2018-06-07", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 10, releaseDate: "2018-06-07", avgEpisodeMinutes: 43 }, { season: 2, episodes: 10, releaseDate: "2019-04-04", avgEpisodeMinutes: 43 }], timelineOrder: 1005, releaseOrder: 5, parts: [], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-television-abc", criticScore: 92, audienceScore: 66, imdbRating: 6.9, tmdbId: 76669, essentialTier: null, tierNote: "Freeform original, own continuity." },

    // ---------- Marvel Television (Netflix Defenders saga) ----------
    { id: "daredevil-netflix", title: "Marvel's Daredevil", category: "series", releaseDate: "2015-04-10", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 13, releaseDate: "2015-04-10", avgEpisodeMinutes: 54 }, { season: 2, episodes: 13, releaseDate: "2016-03-18", avgEpisodeMinutes: 54 }, { season: 3, episodes: 13, releaseDate: "2018-10-19", avgEpisodeMinutes: 54 }], timelineOrder: 1006, releaseOrder: 6, parts: ["street-level"], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-netflix", criticScore: 98, audienceScore: 92, imdbRating: 8.6, tmdbId: 61177, essentialTier: null, tierNote: "The character later returns properly inside the MCU in Daredevil: Born Again — this Netflix run is the predecessor continuity, generally considered semi-canon at most." },
    { id: "jessica-jones", title: "Marvel's Jessica Jones", category: "series", releaseDate: "2015-11-20", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 13, releaseDate: "2015-11-20", avgEpisodeMinutes: 52 }, { season: 2, episodes: 13, releaseDate: "2018-03-08", avgEpisodeMinutes: 52 }, { season: 3, episodes: 13, releaseDate: "2019-06-14", avgEpisodeMinutes: 52 }], timelineOrder: 1007, releaseOrder: 7, parts: ["street-level"], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-netflix", criticScore: 93, audienceScore: 84, imdbRating: 7.9, tmdbId: 62126, essentialTier: null, tierNote: "Netflix continuity, not MCU canon." },
    { id: "luke-cage", title: "Marvel's Luke Cage", category: "series", releaseDate: "2016-09-30", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 13, releaseDate: "2016-09-30", avgEpisodeMinutes: 55 }, { season: 2, episodes: 13, releaseDate: "2018-06-22", avgEpisodeMinutes: 55 }], timelineOrder: 1008, releaseOrder: 8, parts: ["street-level"], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-netflix", criticScore: 82, audienceScore: 79, imdbRating: 7.3, tmdbId: 62285, essentialTier: null, tierNote: "Netflix continuity, not MCU canon." },
    { id: "iron-fist", title: "Marvel's Iron Fist", category: "series", releaseDate: "2017-03-17", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 13, releaseDate: "2017-03-17", avgEpisodeMinutes: 50 }, { season: 2, episodes: 10, releaseDate: "2018-09-07", avgEpisodeMinutes: 50 }], timelineOrder: 1009, releaseOrder: 9, parts: ["street-level"], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-netflix", criticScore: 20, audienceScore: 58, imdbRating: 6.4, tmdbId: 63153, essentialTier: null, tierNote: "The weakest-reviewed Defenders-line show." },
    { id: "the-defenders", title: "Marvel's The Defenders", category: "series", releaseDate: "2017-08-18", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 8, releaseDate: "2017-08-18", avgEpisodeMinutes: 48 }], timelineOrder: 1010, releaseOrder: 10, parts: ["street-level"], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-netflix", criticScore: 78, audienceScore: 66, imdbRating: 7.1, tmdbId: 69478, essentialTier: null, tierNote: "Crossover of the four Netflix leads." },
    { id: "the-punisher-netflix", title: "Marvel's The Punisher", category: "series", releaseDate: "2017-11-17", released: true, phase: null, saga: "tbd", runtimeMinutes: null, seasons: [{ season: 1, episodes: 13, releaseDate: "2017-11-17", avgEpisodeMinutes: 55 }, { season: 2, episodes: 13, releaseDate: "2019-01-18", avgEpisodeMinutes: 55 }], timelineOrder: 1011, releaseOrder: 11, parts: ["street-level"], postCredit: null, isNonMCU: true, nonMCUGroup: "marvel-netflix", criticScore: 82, audienceScore: 89, imdbRating: 8.0, tmdbId: 76479, essentialTier: null, tierNote: "Distinct Frank Castle continuity from the MCU's own Punisher special." },

    // ---------- Sony's non-MCU Spider-Man Universe (and predecessor Spider-Man films) ----------
    { id: "spider-man-2002", title: "Spider-Man", category: "film", releaseDate: "2002-05-03", released: true, phase: null, saga: "tbd", runtimeMinutes: 121, seasons: null, timelineOrder: 2001, releaseOrder: 1, parts: ["spider-man-mcu"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 90, audienceScore: 90, imdbRating: 7.4, tmdbId: 557, essentialTier: null, tierNote: "Sam Raimi trilogy, pre-MCU. Tobey Maguire's Peter later cameos in No Way Home." },
    { id: "spider-man-2-2004", title: "Spider-Man 2", category: "film", releaseDate: "2004-06-30", released: true, phase: null, saga: "tbd", runtimeMinutes: 127, seasons: null, timelineOrder: 2002, releaseOrder: 2, parts: ["spider-man-mcu"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 93, audienceScore: 94, imdbRating: 7.5, tmdbId: 558, essentialTier: null, tierNote: "Raimi trilogy." },
    { id: "spider-man-3-2007", title: "Spider-Man 3", category: "film", releaseDate: "2007-05-04", released: true, phase: null, saga: "tbd", runtimeMinutes: 139, seasons: null, timelineOrder: 2003, releaseOrder: 3, parts: ["spider-man-mcu"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 63, audienceScore: 62, imdbRating: 6.3, tmdbId: 559, essentialTier: null, tierNote: "Raimi trilogy." },
    { id: "amazing-spider-man", title: "The Amazing Spider-Man", category: "film", releaseDate: "2012-07-03", released: true, phase: null, saga: "tbd", runtimeMinutes: 136, seasons: null, timelineOrder: 2004, releaseOrder: 4, parts: ["spider-man-mcu"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 73, audienceScore: 72, imdbRating: 6.9, tmdbId: 1930, essentialTier: null, tierNote: "Andrew Garfield reboot, own continuity — his Peter later cameos in No Way Home." },
    { id: "amazing-spider-man-2", title: "The Amazing Spider-Man 2", category: "film", releaseDate: "2014-05-02", released: true, phase: null, saga: "tbd", runtimeMinutes: 142, seasons: null, timelineOrder: 2005, releaseOrder: 5, parts: ["spider-man-mcu"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 52, audienceScore: 62, imdbRating: 6.6, tmdbId: 102382, essentialTier: null, tierNote: "Final Garfield-era film before the MCU deal." },
    { id: "venom-2018", title: "Venom", category: "film", releaseDate: "2018-10-05", released: true, phase: null, saga: "tbd", runtimeMinutes: 112, seasons: null, timelineOrder: 2006, releaseOrder: 6, parts: ["spider-man-mcu"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 30, audienceScore: 81, imdbRating: 6.6, tmdbId: 335983, essentialTier: null, tierNote: "Sony's own Spider-Man-adjacent universe, no MCU crossover confirmed on-screen." },
    { id: "venom-let-there-be-carnage", title: "Venom: Let There Be Carnage", category: "film", releaseDate: "2021-10-01", released: true, phase: null, saga: "tbd", runtimeMinutes: 97, seasons: null, timelineOrder: 2007, releaseOrder: 7, parts: ["spider-man-mcu"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 59, audienceScore: 90, imdbRating: 6.2, tmdbId: 580489, essentialTier: null, tierNote: "End-credits briefly puts Eddie Brock in the MCU (Peter Parker's apartment) before undoing it." },
    { id: "morbius", title: "Morbius", category: "film", releaseDate: "2022-04-01", released: true, phase: null, saga: "tbd", runtimeMinutes: 104, seasons: null, timelineOrder: 2008, releaseOrder: 8, parts: ["spider-man-mcu"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 16, audienceScore: 53, imdbRating: 5.2, tmdbId: 611090, essentialTier: null, tierNote: "Widely panned; internet-meme notoriety." },
    { id: "madame-web", title: "Madame Web", category: "film", releaseDate: "2024-02-14", released: true, phase: null, saga: "tbd", runtimeMinutes: 116, seasons: null, timelineOrder: 2009, releaseOrder: 9, parts: ["spider-man-mcu"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 12, audienceScore: 34, imdbRating: 4.5, tmdbId: null, essentialTier: null, tierNote: "Lowest-reviewed Sony Spider-Man-universe film to date." },
    { id: "venom-the-last-dance", title: "Venom: The Last Dance", category: "film", releaseDate: "2024-10-25", released: true, phase: null, saga: "tbd", runtimeMinutes: 109, seasons: null, timelineOrder: 2010, releaseOrder: 10, parts: ["spider-man-mcu"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 39, audienceScore: 84, imdbRating: 5.9, tmdbId: 912649, essentialTier: null, tierNote: "Closes the Hardy Venom trilogy." },
    { id: "kraven-the-hunter", title: "Kraven the Hunter", category: "film", releaseDate: "2024-12-13", released: true, phase: null, saga: "tbd", runtimeMinutes: 127, seasons: null, timelineOrder: 2011, releaseOrder: 11, parts: ["spider-man-mcu"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "sony-spiderverse", criticScore: 14, audienceScore: 71, imdbRating: 5.5, tmdbId: 539972, essentialTier: null, tierNote: "Sony's lowest-grossing Spider-Man-universe entry." },

    // ---------- 20th Century Fox: X-Men / Fantastic Four / Deadpool / Blade (pre-Disney merger) ----------
    { id: "blade-1998", title: "Blade", category: "film", releaseDate: "1998-08-21", released: true, phase: null, saga: "tbd", runtimeMinutes: 120, seasons: null, timelineOrder: 3001, releaseOrder: 1, parts: [], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "blade-original", criticScore: 55, audienceScore: 71, imdbRating: 7.1, tmdbId: 1586, essentialTier: null, tierNote: "The original New Line Cinema trilogy, predates the MCU by a decade." },
    { id: "blade-2", title: "Blade II", category: "film", releaseDate: "2002-03-22", released: true, phase: null, saga: "tbd", runtimeMinutes: 117, seasons: null, timelineOrder: 3002, releaseOrder: 2, parts: [], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "blade-original", criticScore: 58, audienceScore: 72, imdbRating: 6.7, tmdbId: 1587, essentialTier: null, tierNote: "Directed by Guillermo del Toro." },
    { id: "blade-trinity", title: "Blade: Trinity", category: "film", releaseDate: "2004-12-08", released: true, phase: null, saga: "tbd", runtimeMinutes: 113, seasons: null, timelineOrder: 3003, releaseOrder: 3, parts: [], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "blade-original", criticScore: 26, audienceScore: 47, imdbRating: 5.9, tmdbId: 9788, essentialTier: null, tierNote: "Closes the original trilogy before an MCU Blade reboot is developed." },
    { id: "x-men-2000", title: "X-Men", category: "film", releaseDate: "2000-07-14", released: true, phase: null, saga: "tbd", runtimeMinutes: 104, seasons: null, timelineOrder: 3010, releaseOrder: 4, parts: ["x-men-fox"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 82, audienceScore: 73, imdbRating: 7.3, tmdbId: 36657, essentialTier: null, tierNote: "Launched the Fox X-Men franchise." },
    { id: "x2", title: "X2", category: "film", releaseDate: "2003-05-02", released: true, phase: null, saga: "tbd", runtimeMinutes: 133, seasons: null, timelineOrder: 3011, releaseOrder: 5, parts: ["x-men-fox"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 87, audienceScore: 87, imdbRating: 7.5, tmdbId: 36658, essentialTier: null, tierNote: "Widely considered the best of the original Fox trilogy." },
    { id: "x-men-last-stand", title: "X-Men: The Last Stand", category: "film", releaseDate: "2006-05-26", released: true, phase: null, saga: "tbd", runtimeMinutes: 104, seasons: null, timelineOrder: 3012, releaseOrder: 6, parts: ["x-men-fox"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 58, audienceScore: 62, imdbRating: 6.7, tmdbId: 36668, essentialTier: null, tierNote: "Closes the original trilogy." },
    { id: "fantastic-four-2005", title: "Fantastic Four", category: "film", releaseDate: "2005-07-08", released: true, phase: null, saga: "tbd", runtimeMinutes: 106, seasons: null, timelineOrder: 3020, releaseOrder: 7, parts: ["fantastic-four"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 27, audienceScore: 40, imdbRating: 5.7, tmdbId: 9738, essentialTier: null, tierNote: "Fox's first Fantastic Four attempt, unrelated to the MCU's own First Steps." },
    { id: "fantastic-four-silver-surfer", title: "Fantastic Four: Rise of the Silver Surfer", category: "film", releaseDate: "2007-06-15", released: true, phase: null, saga: "tbd", runtimeMinutes: 92, seasons: null, timelineOrder: 3021, releaseOrder: 8, parts: ["fantastic-four"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 37, audienceScore: 48, imdbRating: 5.6, tmdbId: 4477, essentialTier: null, tierNote: "Fox era." },
    { id: "x-men-origins-wolverine", title: "X-Men Origins: Wolverine", category: "film", releaseDate: "2009-05-01", released: true, phase: null, saga: "tbd", runtimeMinutes: 107, seasons: null, timelineOrder: 3013, releaseOrder: 9, parts: ["x-men-fox", "wolverine-deadpool"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 38, audienceScore: 54, imdbRating: 6.5, tmdbId: 8835, essentialTier: null, tierNote: "First standalone Wolverine film, poorly reviewed." },
    { id: "x-men-first-class", title: "X-Men: First Class", category: "film", releaseDate: "2011-06-03", released: true, phase: null, saga: "tbd", runtimeMinutes: 131, seasons: null, timelineOrder: 3014, releaseOrder: 10, parts: ["x-men-fox"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 87, audienceScore: 87, imdbRating: 7.6, tmdbId: 49538, essentialTier: null, tierNote: "Prequel reboot, well received." },
    { id: "the-wolverine", title: "The Wolverine", category: "film", releaseDate: "2013-07-26", released: true, phase: null, saga: "tbd", runtimeMinutes: 126, seasons: null, timelineOrder: 3015, releaseOrder: 11, parts: ["x-men-fox", "wolverine-deadpool"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 69, audienceScore: 70, imdbRating: 6.7, tmdbId: 76170, essentialTier: null, tierNote: "Sets up Days of Future Past's mid-credits scene." },
    { id: "x-men-days-of-future-past", title: "X-Men: Days of Future Past", category: "film", releaseDate: "2014-05-23", released: true, phase: null, saga: "tbd", runtimeMinutes: 132, seasons: null, timelineOrder: 3016, releaseOrder: 12, parts: ["x-men-fox"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 90, audienceScore: 90, imdbRating: 7.9, tmdbId: 127585, essentialTier: null, tierNote: "Merges both Fox X-Men timelines." },
    { id: "deadpool-2016", title: "Deadpool", category: "film", releaseDate: "2016-02-12", released: true, phase: null, saga: "tbd", runtimeMinutes: 108, seasons: null, timelineOrder: 3017, releaseOrder: 13, parts: ["wolverine-deadpool"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 84, audienceScore: 90, imdbRating: 8.0, tmdbId: 293660, essentialTier: null, tierNote: "Later officially folded into MCU canon via Deadpool & Wolverine." },
    { id: "x-men-apocalypse", title: "X-Men: Apocalypse", category: "film", releaseDate: "2016-05-27", released: true, phase: null, saga: "tbd", runtimeMinutes: 144, seasons: null, timelineOrder: 3018, releaseOrder: 14, parts: ["x-men-fox"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 47, audienceScore: 66, imdbRating: 6.8, tmdbId: 246655, essentialTier: null, tierNote: "Fox era, weaker reception." },
    { id: "logan", title: "Logan", category: "film", releaseDate: "2017-03-03", released: true, phase: null, saga: "tbd", runtimeMinutes: 137, seasons: null, timelineOrder: 3019, releaseOrder: 15, parts: ["x-men-fox", "wolverine-deadpool"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 93, audienceScore: 89, imdbRating: 8.1, tmdbId: 263115, essentialTier: null, tierNote: "Widely regarded as the best Fox X-Men-adjacent film; standalone story." },
    { id: "deadpool-2", title: "Deadpool 2", category: "film", releaseDate: "2018-05-18", released: true, phase: null, saga: "tbd", runtimeMinutes: 119, seasons: null, timelineOrder: 3022, releaseOrder: 16, parts: ["wolverine-deadpool"], postCredit: { mid: false, end: true }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 84, audienceScore: 88, imdbRating: 7.6, tmdbId: 383498, essentialTier: null, tierNote: "Also folded into MCU canon via Deadpool & Wolverine's references." },
    { id: "dark-phoenix", title: "Dark Phoenix", category: "film", releaseDate: "2019-06-07", released: true, phase: null, saga: "tbd", runtimeMinutes: 113, seasons: null, timelineOrder: 3023, releaseOrder: 17, parts: ["x-men-fox"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 22, audienceScore: 55, imdbRating: 5.7, tmdbId: 316029, essentialTier: null, tierNote: "Final entry in the prequel-era X-Men line." },
    { id: "new-mutants", title: "The New Mutants", category: "film", releaseDate: "2020-08-28", released: true, phase: null, saga: "tbd", runtimeMinutes: 94, seasons: null, timelineOrder: 3024, releaseOrder: 18, parts: ["x-men-fox"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 32, audienceScore: 56, imdbRating: 5.7, tmdbId: 39017, essentialTier: null, tierNote: "Last Fox X-Men-universe film released; delayed for years by the Disney/Fox merger." },
    { id: "fantastic-four-2015", title: "Fant4stic", category: "film", releaseDate: "2015-08-07", released: true, phase: null, saga: "tbd", runtimeMinutes: 100, seasons: null, timelineOrder: 3025, releaseOrder: 19, parts: ["fantastic-four"], postCredit: { mid: false, end: false }, isNonMCU: true, nonMCUGroup: "fox-x-men", criticScore: 9, audienceScore: 22, imdbRating: 4.3, tmdbId: 258489, essentialTier: null, tierNote: "Fox's second, critically panned Fantastic Four attempt." }
  ]
};
